#!/usr/bin/env python3
"""Regenerate docs/description-review-queue.md from data/descriptions.json — deterministic.

The review queue is the human-in-the-loop list of entities whose self-description the crawler +
WAF recovery could not confidently extract (`extraction_empty` / `no_about_found` /
`robots_disallowed`). It must match `descriptions.json` after every recovery batch: entities that
got recovered (`ok`) drop off, and newly-surfaced failures get rows. Excluded by design:
`fetch_failed` (transient WAF bucket, queued for recovery) and `no_url` (upstream data gap).

Determinism + no-clobber: the table is rebuilt from `descriptions.json` (membership + status +
URL) joined with `registry.json` (display names). The "Needed / Resolution" cell is the
status-templated default, EXCEPT that any human-customized note in the current file (a `RESOLVED —
...` annotation, an operator-supplied URL, a site-specific hint) is preserved for an entity that is
still in the queue. So regeneration updates membership without erasing hand-curated resolutions.

Run: `python scripts/build_review_queue.py` (writes the file) or `--check` (diff-only, non-zero if
stale — for CI / pre-PR verification).
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DESCRIPTIONS_PATH = REPO_ROOT / "data" / "descriptions.json"
REGISTRY_PATH = REPO_ROOT / "data" / "registry.json"
QUEUE_PATH = REPO_ROOT / "docs" / "description-review-queue.md"

# Statuses that belong in the queue, in table order.
QUEUE_STATUSES = ("extraction_empty", "no_about_found", "robots_disallowed")
STATUS_ORDER = {s: i for i, s in enumerate(QUEUE_STATUSES)}

DEFAULT_RESOLUTION = {
    "extraction_empty": "Human: check if page is JS-rendered or oddly structured; supply direct URL to the prose",
    "no_about_found": "Human: locate the about/mission page URL (site uses house conventions)",
    "robots_disallowed": "Policy: robots.txt disallows crawling — decide whether to request permission or source text another way",
}

HEADER = """# Description review queue — human in the loop

Entities where the about-crawler (phase 5 + WAF recovery) could not confidently extract a self-description and a human eye is needed. **Update this table whenever descriptions.json changes** (recovery batches must update it in their PRs). Requested by the operator 2026-07-15.

How to resolve a row: find the about/mission page URL by hand, then either give it to the maintainers (an operator-supplied URL gets crawled verbatim next pass) or edit the Resolution column and open a PR.

Not listed here: `fetch_failed` rows (WAF targets queued for recovery batches — transient) and `no_url` entities (no website in ANY source; an upstream-data gap, tracked separately).

This file is regenerated by `scripts/build_review_queue.py` (deterministic; preserves human-edited Resolution notes for rows that persist).

| Entity | id | URL tried | Status | Needed / Resolution |
|---|---|---|---|---|
"""

_ROW_RE = re.compile(r"^\|\s*(?P<name>.*?)\s*\|\s*`(?P<id>[^`]+)`\s*\|\s*(?P<url>.*?)\s*\|"
                     r"\s*`(?P<status>[^`]+)`\s*\|\s*(?P<resolution>.*?)\s*\|\s*$")


def parse_existing_customs(path: Path) -> dict[str, str]:
    """Map id -> resolution text, but only where it differs from the status default (human edits)."""
    customs: dict[str, str] = {}
    if not path.exists():
        return customs
    for line in path.read_text(encoding="utf-8").splitlines():
        m = _ROW_RE.match(line)
        if not m:
            continue
        status = m.group("status")
        resolution = m.group("resolution")
        if resolution and resolution != DEFAULT_RESOLUTION.get(status):
            customs[m.group("id")] = resolution
    return customs


def build_rows(descriptions: dict, names: dict, customs: dict[str, str]) -> list[tuple]:
    rows = []
    for entity_id, rec in descriptions.items():
        status = rec.get("status")
        if status not in QUEUE_STATUSES:
            continue
        name = names.get(entity_id, entity_id.replace("-", " ").title())
        url = rec.get("source_url") or ""
        resolution = customs.get(entity_id, DEFAULT_RESOLUTION[status])
        rows.append((STATUS_ORDER[status], entity_id, name, url, status, resolution))
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


def render(rows: list[tuple], note_date: str) -> str:
    lines = [HEADER.rstrip("\n")]
    for _order, entity_id, name, url, status, resolution in rows:
        lines.append(f"| {name} | `{entity_id}` | {url} | `{status}` | {resolution} |")
    lines.append("")
    lines.append(f"_{len(rows)} rows. Generated from data/descriptions.json ({note_date})._")
    return "\n".join(lines) + "\n"


def generate(note_date: str | None = None) -> str:
    descriptions = json.loads(DESCRIPTIONS_PATH.read_text())["descriptions"]
    entities = json.loads(REGISTRY_PATH.read_text())["entities"]
    names = {e["id"]: e["name"] for e in entities}
    customs = parse_existing_customs(QUEUE_PATH)
    rows = build_rows(descriptions, names, customs)
    return render(rows, note_date or date.today().isoformat())


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate the description review queue.")
    ap.add_argument("--check", action="store_true", help="fail if the file is stale (no write)")
    ap.add_argument("--date", default=None, help="override the footer date (default: today)")
    args = ap.parse_args()

    content = generate(args.date)
    if args.check:
        current = QUEUE_PATH.read_text(encoding="utf-8") if QUEUE_PATH.exists() else ""

        # Compare ignoring the footer date line so a date-only diff isn't flagged.
        def strip(t: str) -> str:
            return re.sub(r"_\d+ rows\. Generated.*?_", "", t)

        if strip(current) != strip(content):
            print("description-review-queue.md is STALE — run scripts/build_review_queue.py")
            return 1
        print("description-review-queue.md is up to date")
        return 0
    QUEUE_PATH.write_text(content, encoding="utf-8")
    n_rows = sum(1 for ln in content.splitlines() if _ROW_RE.match(ln))
    print(f"wrote {QUEUE_PATH} — {n_rows} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
